In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
s = np.array([33,65,50,45])
s

array([33, 65, 50, 45])

In [3]:
s[2]

50

In [4]:
len(s)

4

Дан вектор в Python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. Будем считать, что температура в январе — , то есть отсчёт индексов идёт с нуля.

In [5]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [6]:
print(f'Средняя температура: {t.mean()}')
print(f'Максимальная температура: {t.max()}')
print(f'Минимальная температура: {t.min()}')
print(f'Температура в феврале: {t[1]}')

Средняя температура: 21.25
Максимальная температура: 31
Минимальная температура: 12
Температура в феврале: 14


In [7]:
9+25

34

In [8]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [9]:
a + b

array([15, 23, 14,  8])

In [10]:
a - b

array([ 5, -7, -4, -6])